# 先开启kafka消费者和logger.jar日志采集服务,再开启mock-log.jar发送行为日志
# 外部配置打开
# logging.config=./logback.xml
# 业务日期
mock.date: "2021-10-06"
# 模拟数据发送模式
mock.type: "http"
# http模式下发送的地址,端口号要和logger工程的配置保持一致
mock.url: "http://localhost:8081/applog"
# kafka地址
kafka-server: "localhost:9092"
kafka-topic: "ods_base_log"
# 启动次数
mock.startup.count: 1000
# 设备最大值
mock.max.mid: 20
# 会员最大值
mock.max.uid: 50
# 商品最大值
mock.max.sku-id: 10
# 页面平均访问时间
mock.page.during-time-ms: 20000
# 错误概率 百分比
mock.error.rate: 3
# 每条日志发送延迟 ms
mock.log.sleep: 100
# 商品详情来源  用户查询，商品推广，智能推荐, 促销活动
mock.detail.source-type-rate: "40:25:15:20"
# 领取购物券概率
mock.if_get_coupon_rate: 75
# 购物券最大id
mock.max.coupon-id: 3
# 搜索关键词
mock.search.keyword: "图书,小米,iphone11,电视,口红,ps5,苹果手机,小米盒子"